baseURL = 'https://arjanrijsdijk.com/'
languageCode = 'en-US'
title = 'arjanrijsdijk.com'

  sectionPagesMenu = "main"

  [menu]

    [[menu.main]]
      identifier = "blog"
      title = "Blog"
      url = "/blog"
      weight = 200